// Generated by android-icons/scripts/generate-icon-packs.mjs. Do not edit.
package com.mapconductor.icons.jp

import com.mapconductor.icons.MapIconGlyph

/** jp pack map symbols. Selection is always explicit. */
object JapanMapIcons {
    /** Japanese post office. */
    val postOffice =
        MapIconGlyph(
            id = "jp.post_office",
            pathData = "M4 4 L20 4 L20 7 L4 7 Z M6 9 L18 9 L18 12 L14 12 L14 21 L10 21 L10 12 L6 12 Z",
        )

    /** Japanese police box or koban. */
    val policeBox =
        MapIconGlyph(
            id = "jp.police_box",
            pathData = "M10 2 L14 2 L15 6 L20 9 L18 11 L18 21 L6 21 L6 11 L4 9 L9 6 Z M9 12 L15 12 L15 16 L9 16 Z",
        )

    /** Shinto shrine. */
    val shrine =
        MapIconGlyph(
            id = "jp.shrine",
            pathData = "M3 3 L21 3 L21 6 L3 6 Z M5 8 L19 8 L19 11 L5 11 Z M7 6 L10 6 L9 21 L6 21 Z M14 6 L17 6 L18 21 L15 21 Z",
        )
}
